/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define SRAM_ADDR1 0x20000004UL

int main(void){
	uint32_t var = 0;
	uint32_t volatile *pSRAM_ADDR1 = (uint32_t*)SRAM_ADDR1;
	 /*The volatile qualifier forces the compiler to read
	  *  the value of current address on every access.This
	  *  prevents the compiler from optimizing loop by
	  *  assuming that the memory content does not change outside
	  *  of the program.
	  *
	  *  This is required when the memory location can be modified by
	  *  hardware, DMA, or another execution context.*/

	while(1){
		var = *pSRAM_ADDR1;
		if(var) break;
	}

	while(1);

	return EXIT_SUCCESS;
}
